services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: torticloud-db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - proxy
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" -b -No
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: OctagramDelivery.Api/Dockerfile
    container_name: torticloud-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=TortiCloudDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      - Jwt__Key=EstaEsUnaSuperClaveSecretaParaJWTMuyLargaYSegura_TortiCloud_2026!
      - Jwt__Issuer=torticloud-api.endevour.mx
      - Jwt__Audience=torticloud-app.endevour.mx
    networks:
      - proxy

  client:
    build:
      context: .
      dockerfile: OctagramDelivery.Client/Dockerfile
    container_name: torticloud-client
    restart: unless-stopped
    networks:
      - proxy

volumes:
  sql_data:

networks:
  proxy:
    external: true
